#!/usr/bin/env bash
# Backend app-setup. Run from anywhere: ./server/setup.sh (or: npm run setup)
#
# Installs the generic root orchestrator into the parent ("root") dir and then
# RUNS it, so one command takes you from a fresh clone to a configured stack.
# Pass --deposit-only to install it without running (scripted/CI use).
#
# What lands in root is a thin WRAPPER that execs this repo's deploy/setup.sh.
# It used to be a copy, which meant `git pull` silently left root running an old
# orchestrator — a trap recorded in docs/history.md 2026-08-03 and hit in
# practice. A wrapper cannot go stale.
#
# The compose fragments stay in this repo's deploy/ dir; the orchestrator
# references them in place by absolute path, so nothing docker-specific litters
# the root and a pm2-only user gets no compose files at all. Environment-agnostic;
# the environment is chosen later by the root setup.sh.
set -euo pipefail

RUN=1
for arg in "$@"; do
	case "$arg" in
		--deposit-only|-n) RUN=0 ;;
		*) echo "unknown option: $arg (only --deposit-only is accepted)" >&2; exit 2 ;;
	esac
done
cd "$(dirname "$0")"          # -> server/ (repo root, whatever it's named)
ROOT=".."

# The orchestrator is the only thing that must live in root (so `./setup.sh`
# works there). It auto-detects this repo and the frontend repo by marker files,
# so the folder names are irrelevant.
SERVER_DIR=$(pwd)
cat > "$ROOT"/setup.sh <<WRAPPER
#!/usr/bin/env bash
# Generated by the backend repo's setup.sh. A WRAPPER, not a copy: the real
# orchestrator lives in the backend repo and is updated by \`git pull\`.
# Regenerate this file (e.g. after moving the repo) with: npm run setup
JOUST_DEPLOY_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)" \\
	exec "$SERVER_DIR/deploy/setup.sh" "\$@"
WRAPPER
chmod +x "$ROOT"/setup.sh
chmod +x deploy/setup.sh

# If root is a git repo, keep the generated/machine-specific artifacts out of it.
# (Only the orchestrator + the files IT generates ever land here now.)
GI="$ROOT/.gitignore"
if [ -f "$GI" ] && ! grep -q 'deploy generated (setup.sh)' "$GI"; then
	cat >> "$GI" <<'EOF'

# deploy generated (setup.sh) — machine-specific, not source
/setup.sh
/deploy.conf
/.env
/ecosystem.config.js
/Caddyfile
/joust.service
/images/
EOF
fi

ROOT_ABS=$(cd "$ROOT" && pwd)
echo "✓ root orchestrator installed: $ROOT_ABS/setup.sh -> $SERVER_DIR/deploy/setup.sh"

if [ "$RUN" -eq 0 ]; then
	echo "  next: run ./setup.sh in $ROOT_ABS. (The frontend's 'npm run setup' is"
	echo "        optional — the orchestrator finds both repos automatically.)"
	exit 0
fi

# The orchestrator must run FROM root: it detects both repos by scanning that
# directory, and writes .env / deploy.conf / Caddyfile there.
cd "$ROOT_ABS"
echo
exec ./setup.sh
