-- Awards: an admin-managed catalog of medals and plaques, and the grants that
-- give them to people (todo.md obj. 4.1). Generated by `prisma migrate diff`,
-- then extended with the two invariants below that Prisma cannot express.

-- CreateEnum
CREATE TYPE "AwardKind" AS ENUM ('MEDAL', 'PLAQUE');
-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'AWARD_RECEIVED';
-- CreateTable
CREATE TABLE "Award" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "kind" "AwardKind" NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdById" TEXT,
    "archivedAt" TIMESTAMP(3),
    CONSTRAINT "Award_pkey" PRIMARY KEY ("id")
);
-- CreateTable
CREATE TABLE "UserAward" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "awardId" TEXT NOT NULL,
    "awardedById" TEXT,
    "awardedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" TEXT,
    "pinSlot" INTEGER,
    "displayed" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "UserAward_pkey" PRIMARY KEY ("id")
);
-- CreateIndex
CREATE INDEX "Award_kind_idx" ON "Award"("kind");
-- CreateIndex
CREATE INDEX "UserAward_userId_idx" ON "UserAward"("userId");
-- CreateIndex
CREATE INDEX "UserAward_awardId_idx" ON "UserAward"("awardId");
-- CreateIndex
CREATE UNIQUE INDEX "UserAward_userId_pinSlot_key" ON "UserAward"("userId", "pinSlot");
-- AddForeignKey
ALTER TABLE "Award" ADD CONSTRAINT "Award_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "UserAward" ADD CONSTRAINT "UserAward_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "UserAward" ADD CONSTRAINT "UserAward_awardId_fkey" FOREIGN KEY ("awardId") REFERENCES "Award"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "UserAward" ADD CONSTRAINT "UserAward_awardedById_fkey" FOREIGN KEY ("awardedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ── Invariants the schema cannot state ─────────────────────────────────────

-- A medal is pinned to slot 1, 2 or 3. The unique (userId, pinSlot) index
-- above stops two medals sharing a slot; this stops a slot 4 existing at all.
ALTER TABLE "UserAward"
  ADD CONSTRAINT "UserAward_pinSlot_range" CHECK ("pinSlot" IS NULL OR "pinSlot" BETWEEN 1 AND 3);

-- At most one plaque displayed under a user's name. A partial unique index,
-- so it holds even if two showcase saves race — the service clears the old
-- flag and sets the new one in a single transaction, and this is the backstop.
CREATE UNIQUE INDEX "UserAward_one_displayed_per_user"
  ON "UserAward"("userId") WHERE "displayed";
