-- Tournament builds, profile galleries and moderation (todo.md obj. 4.3 design).
-- Generated by `prisma migrate diff`, then extended with the partial unique
-- indexes below, which Prisma cannot express.


-- CreateEnum
CREATE TYPE "BuildKind" AS ENUM ('IMAGE', 'TEXT', 'LINK');

-- CreateEnum
CREATE TYPE "BuildStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "BuildVisibility" AS ENUM ('PUBLIC', 'AFTER_COMPLETION', 'STAFF_ONLY');

-- CreateEnum
CREATE TYPE "ReportReason" AS ENUM ('SPAM', 'OFFENSIVE', 'NOT_A_BUILD', 'OTHER');

-- CreateEnum
CREATE TYPE "ReportStatus" AS ENUM ('OPEN', 'RESOLVED', 'DISMISSED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "NotificationType" ADD VALUE 'BUILD_REVIEWED';
ALTER TYPE "NotificationType" ADD VALUE 'CONTENT_REMOVED';

-- AlterEnum
ALTER TYPE "AuditCategory" ADD VALUE 'MODERATION';

-- AlterTable
ALTER TABLE "Tournament" ADD COLUMN     "buildVisibility" "BuildVisibility" NOT NULL DEFAULT 'AFTER_COMPLETION',
ADD COLUMN     "buildsLockAtStart" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "buildsRequired" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "TournamentBuild" (
    "id" TEXT NOT NULL,
    "tournamentId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "kind" "BuildKind" NOT NULL,
    "imageUrl" TEXT,
    "text" TEXT,
    "url" TEXT,
    "status" "BuildStatus" NOT NULL DEFAULT 'PENDING',
    "reviewedById" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "reviewNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "removedAt" TIMESTAMP(3),
    "removedById" TEXT,
    "removalReason" TEXT,

    CONSTRAINT "TournamentBuild_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GalleryImage" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "gameId" TEXT NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "caption" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "removedAt" TIMESTAMP(3),
    "removedById" TEXT,
    "removalReason" TEXT,

    CONSTRAINT "GalleryImage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContentReport" (
    "id" TEXT NOT NULL,
    "galleryImageId" TEXT,
    "tournamentBuildId" TEXT,
    "reporterId" TEXT NOT NULL,
    "reason" "ReportReason" NOT NULL,
    "note" TEXT,
    "fromStaff" BOOLEAN NOT NULL DEFAULT false,
    "status" "ReportStatus" NOT NULL DEFAULT 'OPEN',
    "resolvedById" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ContentReport_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TournamentBuild_tournamentId_idx" ON "TournamentBuild"("tournamentId");

-- CreateIndex
CREATE INDEX "TournamentBuild_userId_idx" ON "TournamentBuild"("userId");

-- CreateIndex
CREATE INDEX "GalleryImage_userId_idx" ON "GalleryImage"("userId");

-- CreateIndex
CREATE INDEX "GalleryImage_gameId_idx" ON "GalleryImage"("gameId");

-- CreateIndex
CREATE INDEX "ContentReport_status_createdAt_idx" ON "ContentReport"("status", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "ContentReport_reporterId_galleryImageId_key" ON "ContentReport"("reporterId", "galleryImageId");

-- CreateIndex
CREATE UNIQUE INDEX "ContentReport_reporterId_tournamentBuildId_key" ON "ContentReport"("reporterId", "tournamentBuildId");

-- AddForeignKey
ALTER TABLE "TournamentBuild" ADD CONSTRAINT "TournamentBuild_tournamentId_fkey" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TournamentBuild" ADD CONSTRAINT "TournamentBuild_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TournamentBuild" ADD CONSTRAINT "TournamentBuild_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GalleryImage" ADD CONSTRAINT "GalleryImage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GalleryImage" ADD CONSTRAINT "GalleryImage_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContentReport" ADD CONSTRAINT "ContentReport_galleryImageId_fkey" FOREIGN KEY ("galleryImageId") REFERENCES "GalleryImage"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContentReport" ADD CONSTRAINT "ContentReport_tournamentBuildId_fkey" FOREIGN KEY ("tournamentBuildId") REFERENCES "TournamentBuild"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContentReport" ADD CONSTRAINT "ContentReport_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ── Partial uniqueness ──────────────────────────────────────────────────────
-- One LIVE build per entrant and one LIVE gallery image per game. A soft-removed
-- row (hidden for 30 days before purge) must not hold the slot, or a player whose
-- build an admin removed could not submit a replacement.
CREATE UNIQUE INDEX "TournamentBuild_one_live_per_entrant"
  ON "TournamentBuild"("tournamentId", "userId") WHERE "removedAt" IS NULL;
CREATE UNIQUE INDEX "GalleryImage_one_live_per_game"
  ON "GalleryImage"("userId", "gameId") WHERE "removedAt" IS NULL;

-- A report targets exactly one thing.
ALTER TABLE "ContentReport" ADD CONSTRAINT "ContentReport_one_target"
  CHECK ((("galleryImageId" IS NOT NULL)::int + ("tournamentBuildId" IS NOT NULL)::int) = 1);
