-- Organizer/admin audit log (todo.md obj. 3.1). Generated by prisma migrate diff.
-- Tournament and target columns deliberately carry no foreign key: an entry
-- recording a deletion must outlive the thing it deleted.


-- CreateEnum
CREATE TYPE "AuditCategory" AS ENUM ('TOURNAMENT', 'PARTICIPANT', 'MATCH', 'STAFF', 'USER', 'AWARD', 'CATALOG', 'SYSTEM');

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actorId" TEXT,
    "actorName" TEXT NOT NULL,
    "actorRoles" TEXT[],
    "category" "AuditCategory" NOT NULL,
    "action" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "tournamentId" TEXT,
    "tournamentName" TEXT,
    "targetUserId" TEXT,
    "targetName" TEXT,
    "metadata" JSONB,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- CreateIndex
CREATE INDEX "AuditLog_actorId_idx" ON "AuditLog"("actorId");

-- CreateIndex
CREATE INDEX "AuditLog_tournamentId_idx" ON "AuditLog"("tournamentId");

-- CreateIndex
CREATE INDEX "AuditLog_category_createdAt_idx" ON "AuditLog"("category", "createdAt");

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

